---
- name: Deploy Flask Hello World
  hosts: server1.example.com
  become: true
  tasks:
    - name: Install Python 3 and pip
      package:
        name:
          - python3
          - python3-pip  # Install pip for Python 3
        state: present
      become: true

    - name: Install Flask
      pip:
        name: flask
        state: present
      become: true

    - name: Create Flask App Directory
      file:
        path: /opt/flask_hello_world
        state: directory
      become: true

    - name: Copy Flask App File
      copy:
        src: files/app.py
        dest: /opt/flask_hello_world/app.py
      become: true

    - name: Run Flask App
      command: python3 /opt/flask_hello_world/app.py
      async: 0
      poll: 0
      become: true

